akka {
  loglevel = "INFO"
  http {
    server {
      idle-timeout = 60s
    }
  }
}

http {
  port = 8080
  port = ${?PORT}
}

storage {
  backend = "in-memory"
  backend = ${?STORAGE_BACKEND}
  dynamodb {
    table = "orders"
    table = ${?DYNAMODB_TABLE}
  }
}
